node_number : 2
node_port : 8080
owned_files_dir : "Node3/ownedFiles/"
new_files_dir : "Node3/newFiles/"
owned_files :
        - "file6"
friend_nodes :
        -
                node_name : 1
                node_port : 8080
        -
                node_name : 2
                node_port : 8081


